### ISSUE TITLE
Erroneous ? being appended to URL's

### ISSUE THREAD

**Issue by unixunion** [NeoLegends/tokio-request#7]
I am trying to make a request to a API which does not tolerate a trailing ? at the end of the request. e.g

    let about_url = format!("{}/about/api", &about_url);
    let future = get(&about_url)
        .header("User-Agent", "solace-provision")
        .header("Authorization", &about_url)
        .send(core.handle());

The generated request URL is containing a trailing ?, even though there are not query parameters. 

     "uri":"http://localhost:8081/SEMP/v2/config/about/api?"

Is it at all possible to drop the ? if no query parameters are encoded into the request?

**Comment by NeoLegends** [comment]
Hey :)

Yes, this should indeed be possible. I, however, suggest you switch to https://crates.io/crates/reqwest instead, which is a much more modern library with the same goal of being very ergonomic. I think I should add a deprecation notice to this library and link to reqwest instead.
